# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QFrame, QGridLayout, QGroupBox, QHBoxLayout,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QSlider, QSpinBox,
    QStackedWidget, QTabWidget, QTableView, QTableWidget,
    QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet(u"#buttonTabAddNew, #buttonTabGenerate, #buttonTabPasswords, #buttonTabHealth {\n"
"	text-align: left;\n"
"	padding-left: 20px;\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"#buttonPasswords, #buttonAddNew, #buttonGenerate, #buttonSecurity {\n"
"	text-align: left;\n"
"	padding-left: 12px;\n"
"	padding-right: 12px;\n"
"}")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        font = QFont()
        font.setFamilies([u"Roboto"])
        self.frame.setFont(font)
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frameSidebar = QFrame(self.frame)
        self.frameSidebar.setObjectName(u"frameSidebar")
        self.frameSidebar.setMinimumSize(QSize(170, 0))
        self.frameSidebar.setMaximumSize(QSize(160, 16777215))
        self.frameSidebar.setFont(font)
        self.frameSidebar.setFrameShape(QFrame.Box)
        self.frameSidebarButtons = QFrame(self.frameSidebar)
        self.frameSidebarButtons.setObjectName(u"frameSidebarButtons")
        self.frameSidebarButtons.setGeometry(QRect(0, 110, 170, 170))
        self.frameSidebarButtons.setMinimumSize(QSize(170, 170))
        self.frameSidebarButtons.setMaximumSize(QSize(170, 170))
        self.frameSidebarButtons.setFont(font)
        self.frameSidebarButtons.setFrameShape(QFrame.NoFrame)
        self.verticalLayout = QVBoxLayout(self.frameSidebarButtons)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonTabPasswords = QPushButton(self.frameSidebarButtons)
        self.buttonTabPasswords.setObjectName(u"buttonTabPasswords")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTabPasswords.sizePolicy().hasHeightForWidth())
        self.buttonTabPasswords.setSizePolicy(sizePolicy)
        self.buttonTabPasswords.setMinimumSize(QSize(0, 30))
        font1 = QFont()
        font1.setFamilies([u"Roboto"])
        font1.setPointSize(9)
        self.buttonTabPasswords.setFont(font1)
        self.buttonTabPasswords.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabPasswords.setLayoutDirection(Qt.LeftToRight)
        self.buttonTabPasswords.setAutoFillBackground(False)
        self.buttonTabPasswords.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u"icons/lock.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabPasswords.setIcon(icon)
        self.buttonTabPasswords.setIconSize(QSize(14, 14))
        self.buttonTabPasswords.setCheckable(False)
        self.buttonTabPasswords.setChecked(False)
        self.buttonTabPasswords.setAutoRepeat(False)
        self.buttonTabPasswords.setAutoExclusive(False)
        self.buttonTabPasswords.setFlat(False)

        self.verticalLayout.addWidget(self.buttonTabPasswords)

        self.buttonTabAddNew = QPushButton(self.frameSidebarButtons)
        self.buttonTabAddNew.setObjectName(u"buttonTabAddNew")
        sizePolicy.setHeightForWidth(self.buttonTabAddNew.sizePolicy().hasHeightForWidth())
        self.buttonTabAddNew.setSizePolicy(sizePolicy)
        self.buttonTabAddNew.setMinimumSize(QSize(0, 30))
        self.buttonTabAddNew.setFont(font1)
        self.buttonTabAddNew.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabAddNew.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u"icons/add.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabAddNew.setIcon(icon1)
        self.buttonTabAddNew.setIconSize(QSize(14, 14))

        self.verticalLayout.addWidget(self.buttonTabAddNew)

        self.buttonTabGenerate = QPushButton(self.frameSidebarButtons)
        self.buttonTabGenerate.setObjectName(u"buttonTabGenerate")
        sizePolicy.setHeightForWidth(self.buttonTabGenerate.sizePolicy().hasHeightForWidth())
        self.buttonTabGenerate.setSizePolicy(sizePolicy)
        self.buttonTabGenerate.setMinimumSize(QSize(0, 30))
        self.buttonTabGenerate.setFont(font1)
        self.buttonTabGenerate.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabGenerate.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u"icons/refresh.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabGenerate.setIcon(icon2)
        self.buttonTabGenerate.setIconSize(QSize(14, 14))

        self.verticalLayout.addWidget(self.buttonTabGenerate)

        self.buttonTabHealth = QPushButton(self.frameSidebarButtons)
        self.buttonTabHealth.setObjectName(u"buttonTabHealth")
        sizePolicy.setHeightForWidth(self.buttonTabHealth.sizePolicy().hasHeightForWidth())
        self.buttonTabHealth.setSizePolicy(sizePolicy)
        self.buttonTabHealth.setMinimumSize(QSize(0, 30))
        self.buttonTabHealth.setFont(font1)
        self.buttonTabHealth.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabHealth.setStyleSheet(u"")
        icon3 = QIcon()
        icon3.addFile(u"icons/security.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabHealth.setIcon(icon3)
        self.buttonTabHealth.setIconSize(QSize(14, 14))

        self.verticalLayout.addWidget(self.buttonTabHealth)

        self.label = QLabel(self.frameSidebar)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 111, 41))
        font2 = QFont()
        font2.setFamilies([u"Roboto Medium"])
        font2.setPointSize(10)
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.buttonLogOut = QPushButton(self.frameSidebar)
        self.buttonLogOut.setObjectName(u"buttonLogOut")
        self.buttonLogOut.setGeometry(QRect(20, 540, 131, 27))
        self.buttonLogOut.setFont(font)
        self.buttonLogOut.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u"icons/log-out.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonLogOut.setIcon(icon4)

        self.horizontalLayout_2.addWidget(self.frameSidebar)

        self.stackedWidget = QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setFont(font)
        self.widgetPasswords = QWidget()
        self.widgetPasswords.setObjectName(u"widgetPasswords")
        self.verticalLayout_3 = QVBoxLayout(self.widgetPasswords)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.framePasswordDashboard = QFrame(self.widgetPasswords)
        self.framePasswordDashboard.setObjectName(u"framePasswordDashboard")
        self.framePasswordDashboard.setFrameShape(QFrame.NoFrame)
        self.framePasswordDashboard.setFrameShadow(QFrame.Raised)
        self.editSearch = QLineEdit(self.framePasswordDashboard)
        self.editSearch.setObjectName(u"editSearch")
        self.editSearch.setGeometry(QRect(40, 100, 530, 25))
        self.editSearch.setMinimumSize(QSize(0, 25))
        self.editSearch.setMaximumSize(QSize(16777215, 25))
        self.editSearch.setFont(font)
        self.editSearch.setInputMethodHints(Qt.ImhLowercaseOnly|Qt.ImhNoAutoUppercase|Qt.ImhPreferLowercase|Qt.ImhPreferNumbers|Qt.ImhPreferUppercase|Qt.ImhUppercaseOnly)
        self.editSearch.setFrame(True)
        self.editSearch.setClearButtonEnabled(True)
        self.tablePasswords = QTableView(self.framePasswordDashboard)
        self.tablePasswords.setObjectName(u"tablePasswords")
        self.tablePasswords.setGeometry(QRect(40, 150, 530, 242))
        self.tablePasswords.setFont(font1)
        self.tablePasswords.setFrameShape(QFrame.StyledPanel)
        self.tablePasswords.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tablePasswords.setAutoScroll(False)
        self.tablePasswords.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tablePasswords.setTabKeyNavigation(False)
        self.tablePasswords.setProperty("showDropIndicator", True)
        self.tablePasswords.setAlternatingRowColors(False)
        self.tablePasswords.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tablePasswords.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablePasswords.horizontalHeader().setMinimumSectionSize(111)
        self.tablePasswords.horizontalHeader().setDefaultSectionSize(111)
        self.tablePasswords.verticalHeader().setVisible(False)
        self.frame_4 = QFrame(self.framePasswordDashboard)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(40, 530, 530, 40))
        self.frame_4.setFont(font1)
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.gridLayout = QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonDelete = QPushButton(self.frame_4)
        self.buttonDelete.setObjectName(u"buttonDelete")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(25)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.buttonDelete.sizePolicy().hasHeightForWidth())
        self.buttonDelete.setSizePolicy(sizePolicy1)
        self.buttonDelete.setMinimumSize(QSize(0, 27))
        font3 = QFont()
        font3.setFamilies([u"Roboto"])
        font3.setPointSize(8)
        self.buttonDelete.setFont(font3)
        self.buttonDelete.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u"icons/trash.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonDelete.setIcon(icon5)
        self.buttonDelete.setIconSize(QSize(13, 13))

        self.gridLayout.addWidget(self.buttonDelete, 0, 2, 1, 1)

        self.buttonCopyPassword = QPushButton(self.frame_4)
        self.buttonCopyPassword.setObjectName(u"buttonCopyPassword")
        sizePolicy1.setHeightForWidth(self.buttonCopyPassword.sizePolicy().hasHeightForWidth())
        self.buttonCopyPassword.setSizePolicy(sizePolicy1)
        self.buttonCopyPassword.setMinimumSize(QSize(0, 27))
        self.buttonCopyPassword.setFont(font3)
        self.buttonCopyPassword.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u"icons/copy.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonCopyPassword.setIcon(icon6)
        self.buttonCopyPassword.setIconSize(QSize(13, 13))

        self.gridLayout.addWidget(self.buttonCopyPassword, 0, 0, 1, 1)

        self.buttonEdit = QPushButton(self.frame_4)
        self.buttonEdit.setObjectName(u"buttonEdit")
        sizePolicy1.setHeightForWidth(self.buttonEdit.sizePolicy().hasHeightForWidth())
        self.buttonEdit.setSizePolicy(sizePolicy1)
        self.buttonEdit.setMinimumSize(QSize(0, 27))
        self.buttonEdit.setFont(font3)
        self.buttonEdit.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u"icons/edit.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonEdit.setIcon(icon7)
        self.buttonEdit.setIconSize(QSize(13, 13))

        self.gridLayout.addWidget(self.buttonEdit, 0, 1, 1, 1)

        self.frame_3 = QFrame(self.framePasswordDashboard)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(40, 20, 530, 45))
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.verticalLayout_17 = QVBoxLayout(self.frame_3)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.labelHeading_4 = QLabel(self.frame_3)
        self.labelHeading_4.setObjectName(u"labelHeading_4")
        font4 = QFont()
        font4.setFamilies([u"Roboto"])
        font4.setPointSize(12)
        self.labelHeading_4.setFont(font4)
        self.labelHeading_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_17.addWidget(self.labelHeading_4)

        self.line = QFrame(self.frame_3)
        self.line.setObjectName(u"line")
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QFrame.HLine)

        self.verticalLayout_17.addWidget(self.line)

        self.frame_2 = QFrame(self.framePasswordDashboard)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(40, 410, 531, 101))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)

        self.verticalLayout_3.addWidget(self.framePasswordDashboard)

        self.stackedWidget.addWidget(self.widgetPasswords)
        self.widgetAdd = QWidget()
        self.widgetAdd.setObjectName(u"widgetAdd")
        self.verticalLayout_4 = QVBoxLayout(self.widgetAdd)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.frameAddPassword = QFrame(self.widgetAdd)
        self.frameAddPassword.setObjectName(u"frameAddPassword")
        self.frameAddPassword.setFont(font)
        self.frameAddPassword.setFrameShape(QFrame.NoFrame)
        self.frameAddPassword.setFrameShadow(QFrame.Raised)
        self.frame_5 = QFrame(self.frameAddPassword)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(40, 20, 530, 45))
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.verticalLayout_18 = QVBoxLayout(self.frame_5)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.labelHeading_5 = QLabel(self.frame_5)
        self.labelHeading_5.setObjectName(u"labelHeading_5")
        self.labelHeading_5.setFont(font4)
        self.labelHeading_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_18.addWidget(self.labelHeading_5)

        self.line_2 = QFrame(self.frame_5)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShadow(QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QFrame.HLine)

        self.verticalLayout_18.addWidget(self.line_2)

        self.buttonAddPassword = QPushButton(self.frameAddPassword)
        self.buttonAddPassword.setObjectName(u"buttonAddPassword")
        self.buttonAddPassword.setGeometry(QRect(420, 480, 151, 27))
        self.buttonAddPassword.setMinimumSize(QSize(0, 27))
        self.buttonAddPassword.setFont(font3)
        self.buttonAddPassword.setCursor(QCursor(Qt.PointingHandCursor))
        self.framePasswordEntry = QFrame(self.frameAddPassword)
        self.framePasswordEntry.setObjectName(u"framePasswordEntry")
        self.framePasswordEntry.setGeometry(QRect(40, 100, 530, 371))
        self.framePasswordEntry.setFrameShape(QFrame.NoFrame)
        self.framePasswordEntry.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.framePasswordEntry)
        self.verticalLayout_7.setSpacing(12)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.groupBox_4 = QGroupBox(self.framePasswordEntry)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setFont(font3)
        self.verticalLayout_15 = QVBoxLayout(self.groupBox_4)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.comboBoxEntryTitle = QComboBox(self.groupBox_4)
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.addItem("")
        self.comboBoxEntryTitle.setObjectName(u"comboBoxEntryTitle")
        self.comboBoxEntryTitle.setFont(font1)
        self.comboBoxEntryTitle.setEditable(True)
        self.comboBoxEntryTitle.setMaxVisibleItems(10)

        self.verticalLayout_15.addWidget(self.comboBoxEntryTitle)


        self.verticalLayout_7.addWidget(self.groupBox_4)

        self.groupBox_5 = QGroupBox(self.framePasswordEntry)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setFont(font3)
        self.verticalLayout_21 = QVBoxLayout(self.groupBox_5)
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.editEntryUrl = QLineEdit(self.groupBox_5)
        self.editEntryUrl.setObjectName(u"editEntryUrl")
        font5 = QFont()
        font5.setFamilies([u"Roboto"])
        font5.setPointSize(10)
        self.editEntryUrl.setFont(font5)
        self.editEntryUrl.setInputMethodHints(Qt.ImhNone)
        self.editEntryUrl.setClearButtonEnabled(True)

        self.verticalLayout_21.addWidget(self.editEntryUrl)


        self.verticalLayout_7.addWidget(self.groupBox_5)

        self.groupBox_6 = QGroupBox(self.framePasswordEntry)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setFont(font3)
        self.verticalLayout_22 = QVBoxLayout(self.groupBox_6)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.editEntryUsername = QLineEdit(self.groupBox_6)
        self.editEntryUsername.setObjectName(u"editEntryUsername")
        self.editEntryUsername.setFont(font5)
        self.editEntryUsername.setClearButtonEnabled(True)

        self.verticalLayout_22.addWidget(self.editEntryUsername)


        self.verticalLayout_7.addWidget(self.groupBox_6)

        self.groupBox_7 = QGroupBox(self.framePasswordEntry)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setFont(font3)
        self.horizontalLayout_5 = QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.editEntryPassword = QLineEdit(self.groupBox_7)
        self.editEntryPassword.setObjectName(u"editEntryPassword")
        self.editEntryPassword.setMinimumSize(QSize(0, 25))
        self.editEntryPassword.setFont(font5)
        self.editEntryPassword.setEchoMode(QLineEdit.Password)
        self.editEntryPassword.setClearButtonEnabled(True)

        self.horizontalLayout_5.addWidget(self.editEntryPassword)

        self.buttonPasswordToggle = QPushButton(self.groupBox_7)
        self.buttonPasswordToggle.setObjectName(u"buttonPasswordToggle")
        self.buttonPasswordToggle.setMinimumSize(QSize(27, 27))
        self.buttonPasswordToggle.setFont(font3)
        self.buttonPasswordToggle.setCursor(QCursor(Qt.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u"icons/eye-crossed.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonPasswordToggle.setIcon(icon8)
        self.buttonPasswordToggle.setIconSize(QSize(14, 14))
        self.buttonPasswordToggle.setCheckable(True)

        self.horizontalLayout_5.addWidget(self.buttonPasswordToggle)


        self.verticalLayout_7.addWidget(self.groupBox_7)

        self.groupBox_12 = QGroupBox(self.framePasswordEntry)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setFont(font3)
        self.horizontalLayout_3 = QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.editEntryPasswordConfirm = QLineEdit(self.groupBox_12)
        self.editEntryPasswordConfirm.setObjectName(u"editEntryPasswordConfirm")
        self.editEntryPasswordConfirm.setMinimumSize(QSize(0, 25))
        self.editEntryPasswordConfirm.setFont(font5)
        self.editEntryPasswordConfirm.setEchoMode(QLineEdit.Password)
        self.editEntryPasswordConfirm.setClearButtonEnabled(True)

        self.horizontalLayout_3.addWidget(self.editEntryPasswordConfirm)

        self.buttonPasswordToggle2 = QPushButton(self.groupBox_12)
        self.buttonPasswordToggle2.setObjectName(u"buttonPasswordToggle2")
        self.buttonPasswordToggle2.setMinimumSize(QSize(27, 27))
        self.buttonPasswordToggle2.setFont(font3)
        self.buttonPasswordToggle2.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonPasswordToggle2.setIcon(icon8)
        self.buttonPasswordToggle2.setIconSize(QSize(14, 14))
        self.buttonPasswordToggle2.setCheckable(True)

        self.horizontalLayout_3.addWidget(self.buttonPasswordToggle2)


        self.verticalLayout_7.addWidget(self.groupBox_12)


        self.verticalLayout_4.addWidget(self.frameAddPassword)

        self.stackedWidget.addWidget(self.widgetAdd)
        self.widgetGenerate = QWidget()
        self.widgetGenerate.setObjectName(u"widgetGenerate")
        self.horizontalLayout_6 = QHBoxLayout(self.widgetGenerate)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.frameGenerate = QFrame(self.widgetGenerate)
        self.frameGenerate.setObjectName(u"frameGenerate")
        font6 = QFont()
        font6.setPointSize(10)
        self.frameGenerate.setFont(font6)
        self.frameGenerate.setFrameShape(QFrame.NoFrame)
        self.frameGenerate.setFrameShadow(QFrame.Raised)
        self.groupBox_2 = QGroupBox(self.frameGenerate)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(39, 230, 530, 71))
        self.groupBox_2.setFont(font3)
        self.horizontalLayout_4 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.spinBox = QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMinimumSize(QSize(0, 25))
        self.spinBox.setFont(font5)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(True)
        self.spinBox.setAccelerated(False)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMinimum(8)
        self.spinBox.setMaximum(50)
        self.spinBox.setValue(15)

        self.horizontalLayout_4.addWidget(self.spinBox)

        self.horizontalSlider = QSlider(self.groupBox_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setMinimumSize(QSize(0, 20))
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalSlider.setMinimum(8)
        self.horizontalSlider.setMaximum(50)
        self.horizontalSlider.setValue(15)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)

        self.horizontalLayout_4.addWidget(self.horizontalSlider)

        self.groupBox = QGroupBox(self.frameGenerate)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(39, 320, 530, 142))
        self.groupBox.setFont(font3)
        self.verticalLayout_5 = QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.checkBoxUpper = QCheckBox(self.groupBox)
        self.checkBoxUpper.setObjectName(u"checkBoxUpper")
        self.checkBoxUpper.setFont(font5)
        self.checkBoxUpper.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxUpper)

        self.checkBoxLower = QCheckBox(self.groupBox)
        self.checkBoxLower.setObjectName(u"checkBoxLower")
        self.checkBoxLower.setFont(font5)
        self.checkBoxLower.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxLower)

        self.checkBoxDigits = QCheckBox(self.groupBox)
        self.checkBoxDigits.setObjectName(u"checkBoxDigits")
        self.checkBoxDigits.setFont(font5)
        self.checkBoxDigits.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxDigits)

        self.checkBoxSymbols = QCheckBox(self.groupBox)
        self.checkBoxSymbols.setObjectName(u"checkBoxSymbols")
        self.checkBoxSymbols.setFont(font5)
        self.checkBoxSymbols.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxSymbols)

        self.groupBox_3 = QGroupBox(self.frameGenerate)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(40, 100, 530, 61))
        self.groupBox_3.setFont(font3)
        self.verticalLayout_11 = QVBoxLayout(self.groupBox_3)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.labelGeneratedPwd = QLabel(self.groupBox_3)
        self.labelGeneratedPwd.setObjectName(u"labelGeneratedPwd")
        font7 = QFont()
        font7.setFamilies([u"Consolas"])
        font7.setPointSize(10)
        self.labelGeneratedPwd.setFont(font7)
        self.labelGeneratedPwd.setCursor(QCursor(Qt.IBeamCursor))
        self.labelGeneratedPwd.setFrameShape(QFrame.StyledPanel)
        self.labelGeneratedPwd.setFrameShadow(QFrame.Plain)
        self.labelGeneratedPwd.setWordWrap(False)
        self.labelGeneratedPwd.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextSelectableByMouse)

        self.verticalLayout_11.addWidget(self.labelGeneratedPwd)

        self.frameFormButtons_2 = QFrame(self.frameGenerate)
        self.frameFormButtons_2.setObjectName(u"frameFormButtons_2")
        self.frameFormButtons_2.setGeometry(QRect(40, 170, 261, 31))
        self.frameFormButtons_2.setFont(font)
        self.frameFormButtons_2.setFrameShape(QFrame.NoFrame)
        self.horizontalLayout_9 = QHBoxLayout(self.frameFormButtons_2)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.buttonRegenerate = QPushButton(self.frameFormButtons_2)
        self.buttonRegenerate.setObjectName(u"buttonRegenerate")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.buttonRegenerate.sizePolicy().hasHeightForWidth())
        self.buttonRegenerate.setSizePolicy(sizePolicy2)
        self.buttonRegenerate.setMinimumSize(QSize(120, 27))
        self.buttonRegenerate.setMaximumSize(QSize(120, 27))
        self.buttonRegenerate.setFont(font)
        self.buttonRegenerate.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonRegenerate.setIcon(icon2)
        self.buttonRegenerate.setIconSize(QSize(10, 10))

        self.horizontalLayout_9.addWidget(self.buttonRegenerate)

        self.buttonCopyRandomPassword = QPushButton(self.frameFormButtons_2)
        self.buttonCopyRandomPassword.setObjectName(u"buttonCopyRandomPassword")
        sizePolicy2.setHeightForWidth(self.buttonCopyRandomPassword.sizePolicy().hasHeightForWidth())
        self.buttonCopyRandomPassword.setSizePolicy(sizePolicy2)
        self.buttonCopyRandomPassword.setMinimumSize(QSize(135, 27))
        self.buttonCopyRandomPassword.setMaximumSize(QSize(135, 27))
        self.buttonCopyRandomPassword.setFont(font)
        self.buttonCopyRandomPassword.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonCopyRandomPassword.setIcon(icon6)
        self.buttonCopyRandomPassword.setIconSize(QSize(10, 10))

        self.horizontalLayout_9.addWidget(self.buttonCopyRandomPassword)

        self.frame_6 = QFrame(self.frameGenerate)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(40, 20, 530, 45))
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.verticalLayout_19 = QVBoxLayout(self.frame_6)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.labelHeading_6 = QLabel(self.frame_6)
        self.labelHeading_6.setObjectName(u"labelHeading_6")
        self.labelHeading_6.setFont(font4)
        self.labelHeading_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_19.addWidget(self.labelHeading_6)

        self.line_3 = QFrame(self.frame_6)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShadow(QFrame.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QFrame.HLine)

        self.verticalLayout_19.addWidget(self.line_3)


        self.horizontalLayout_6.addWidget(self.frameGenerate)

        self.stackedWidget.addWidget(self.widgetGenerate)
        self.widgetHealth = QWidget()
        self.widgetHealth.setObjectName(u"widgetHealth")
        self.horizontalLayout_7 = QHBoxLayout(self.widgetHealth)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.frameSecurity = QFrame(self.widgetHealth)
        self.frameSecurity.setObjectName(u"frameSecurity")
        self.frameSecurity.setFrameShape(QFrame.NoFrame)
        self.frameSecurity.setFrameShadow(QFrame.Sunken)
        self.frame_12 = QFrame(self.frameSecurity)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(40, 20, 530, 45))
        self.frame_12.setFrameShape(QFrame.NoFrame)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.verticalLayout_20 = QVBoxLayout(self.frame_12)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.labelHeading_7 = QLabel(self.frame_12)
        self.labelHeading_7.setObjectName(u"labelHeading_7")
        self.labelHeading_7.setFont(font4)
        self.labelHeading_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.verticalLayout_20.addWidget(self.labelHeading_7)

        self.line_4 = QFrame(self.frame_12)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShadow(QFrame.Plain)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QFrame.HLine)

        self.verticalLayout_20.addWidget(self.line_4)

        self.tabWidget = QTabWidget(self.frameSecurity)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(40, 230, 530, 331))
        font8 = QFont()
        font8.setFamilies([u"Roboto Medium"])
        self.tabWidget.setFont(font8)
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabCompromised = QWidget()
        self.tabCompromised.setObjectName(u"tabCompromised")
        self.verticalLayout_23 = QVBoxLayout(self.tabCompromised)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.tableCompromised = QTableWidget(self.tabCompromised)
        if (self.tableCompromised.columnCount() < 3):
            self.tableCompromised.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableCompromised.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableCompromised.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableCompromised.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.tableCompromised.setObjectName(u"tableCompromised")
        self.tableCompromised.setFont(font)
        self.tableCompromised.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableCompromised.setTabKeyNavigation(True)
        self.tableCompromised.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableCompromised.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableCompromised.setSortingEnabled(False)
        self.tableCompromised.horizontalHeader().setMinimumSectionSize(141)
        self.tableCompromised.horizontalHeader().setDefaultSectionSize(141)

        self.verticalLayout_23.addWidget(self.tableCompromised)

        self.tabWidget.addTab(self.tabCompromised, "")
        self.tabReused = QWidget()
        self.tabReused.setObjectName(u"tabReused")
        self.verticalLayout_30 = QVBoxLayout(self.tabReused)
        self.verticalLayout_30.setObjectName(u"verticalLayout_30")
        self.tableReused = QTableWidget(self.tabReused)
        if (self.tableReused.columnCount() < 3):
            self.tableReused.setColumnCount(3)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableReused.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableReused.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableReused.setHorizontalHeaderItem(2, __qtablewidgetitem5)
        self.tableReused.setObjectName(u"tableReused")
        self.tableReused.setFont(font)
        self.tableReused.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableReused.setTabKeyNavigation(True)
        self.tableReused.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableReused.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableReused.setSortingEnabled(False)
        self.tableReused.horizontalHeader().setMinimumSectionSize(141)
        self.tableReused.horizontalHeader().setDefaultSectionSize(141)

        self.verticalLayout_30.addWidget(self.tableReused)

        self.tabWidget.addTab(self.tabReused, "")
        self.tabWeak = QWidget()
        self.tabWeak.setObjectName(u"tabWeak")
        self.verticalLayout_31 = QVBoxLayout(self.tabWeak)
        self.verticalLayout_31.setObjectName(u"verticalLayout_31")
        self.tableWeak = QTableWidget(self.tabWeak)
        if (self.tableWeak.columnCount() < 3):
            self.tableWeak.setColumnCount(3)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWeak.setHorizontalHeaderItem(0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWeak.setHorizontalHeaderItem(1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWeak.setHorizontalHeaderItem(2, __qtablewidgetitem8)
        self.tableWeak.setObjectName(u"tableWeak")
        self.tableWeak.setFont(font)
        self.tableWeak.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWeak.setTabKeyNavigation(True)
        self.tableWeak.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWeak.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWeak.setSortingEnabled(False)
        self.tableWeak.horizontalHeader().setMinimumSectionSize(141)
        self.tableWeak.horizontalHeader().setDefaultSectionSize(141)

        self.verticalLayout_31.addWidget(self.tableWeak)

        self.tabWidget.addTab(self.tabWeak, "")
        self.tabSafe = QWidget()
        self.tabSafe.setObjectName(u"tabSafe")
        self.verticalLayout_32 = QVBoxLayout(self.tabSafe)
        self.verticalLayout_32.setObjectName(u"verticalLayout_32")
        self.tableSafe = QTableWidget(self.tabSafe)
        if (self.tableSafe.columnCount() < 3):
            self.tableSafe.setColumnCount(3)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.tableSafe.setHorizontalHeaderItem(0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableSafe.setHorizontalHeaderItem(1, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.tableSafe.setHorizontalHeaderItem(2, __qtablewidgetitem11)
        self.tableSafe.setObjectName(u"tableSafe")
        self.tableSafe.setFont(font)
        self.tableSafe.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableSafe.setTabKeyNavigation(True)
        self.tableSafe.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableSafe.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableSafe.setSortingEnabled(False)
        self.tableSafe.horizontalHeader().setMinimumSectionSize(141)
        self.tableSafe.horizontalHeader().setDefaultSectionSize(141)

        self.verticalLayout_32.addWidget(self.tableSafe)

        self.tabWidget.addTab(self.tabSafe, "")
        self.frame_7 = QFrame(self.frameSecurity)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(40, 150, 531, 61))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Plain)
        self.horizontalLayout = QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.groupBox_13 = QGroupBox(self.frame_7)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setMinimumSize(QSize(108, 0))
        self.groupBox_13.setMaximumSize(QSize(108, 16777215))
        self.groupBox_13.setFont(font)
        self.groupBox_13.setAlignment(Qt.AlignCenter)
        self.groupBox_13.setFlat(False)
        self.verticalLayout_24 = QVBoxLayout(self.groupBox_13)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(-1, 4, -1, 4)
        self.labelTotalPasswords = QLabel(self.groupBox_13)
        self.labelTotalPasswords.setObjectName(u"labelTotalPasswords")
        self.labelTotalPasswords.setFont(font5)
        self.labelTotalPasswords.setInputMethodHints(Qt.ImhNone)
        self.labelTotalPasswords.setFrameShape(QFrame.NoFrame)
        self.labelTotalPasswords.setAlignment(Qt.AlignCenter)

        self.verticalLayout_24.addWidget(self.labelTotalPasswords)


        self.horizontalLayout.addWidget(self.groupBox_13)

        self.groupBox_14 = QGroupBox(self.frame_7)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setMinimumSize(QSize(97, 0))
        self.groupBox_14.setMaximumSize(QSize(97, 16777215))
        self.groupBox_14.setFont(font)
        self.groupBox_14.setAlignment(Qt.AlignCenter)
        self.groupBox_14.setFlat(False)
        self.verticalLayout_12 = QVBoxLayout(self.groupBox_14)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(-1, 4, -1, 4)
        self.labelCompromised = QLabel(self.groupBox_14)
        self.labelCompromised.setObjectName(u"labelCompromised")
        self.labelCompromised.setFont(font5)
        self.labelCompromised.setInputMethodHints(Qt.ImhNone)
        self.labelCompromised.setFrameShape(QFrame.NoFrame)
        self.labelCompromised.setAlignment(Qt.AlignCenter)

        self.verticalLayout_12.addWidget(self.labelCompromised)


        self.horizontalLayout.addWidget(self.groupBox_14)

        self.groupBox_8 = QGroupBox(self.frame_7)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setMinimumSize(QSize(62, 0))
        self.groupBox_8.setMaximumSize(QSize(62, 16777215))
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(Qt.AlignCenter)
        self.groupBox_8.setFlat(False)
        self.verticalLayout_13 = QVBoxLayout(self.groupBox_8)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(-1, 4, -1, 4)
        self.labelReused = QLabel(self.groupBox_8)
        self.labelReused.setObjectName(u"labelReused")
        self.labelReused.setFont(font5)
        self.labelReused.setInputMethodHints(Qt.ImhNone)
        self.labelReused.setFrameShape(QFrame.NoFrame)
        self.labelReused.setAlignment(Qt.AlignCenter)

        self.verticalLayout_13.addWidget(self.labelReused)


        self.horizontalLayout.addWidget(self.groupBox_8)

        self.groupBox_9 = QGroupBox(self.frame_7)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setMinimumSize(QSize(51, 0))
        self.groupBox_9.setMaximumSize(QSize(51, 16777215))
        self.groupBox_9.setFont(font)
        self.groupBox_9.setAlignment(Qt.AlignCenter)
        self.groupBox_9.setFlat(False)
        self.verticalLayout_14 = QVBoxLayout(self.groupBox_9)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(-1, 4, -1, 4)
        self.labelWeak = QLabel(self.groupBox_9)
        self.labelWeak.setObjectName(u"labelWeak")
        self.labelWeak.setFont(font5)
        self.labelWeak.setInputMethodHints(Qt.ImhNone)
        self.labelWeak.setFrameShape(QFrame.NoFrame)
        self.labelWeak.setAlignment(Qt.AlignCenter)

        self.verticalLayout_14.addWidget(self.labelWeak)


        self.horizontalLayout.addWidget(self.groupBox_9)

        self.groupBox_10 = QGroupBox(self.frame_7)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setMinimumSize(QSize(46, 0))
        self.groupBox_10.setMaximumSize(QSize(46, 16777215))
        self.groupBox_10.setFont(font)
        self.groupBox_10.setAlignment(Qt.AlignCenter)
        self.groupBox_10.setFlat(False)
        self.verticalLayout_16 = QVBoxLayout(self.groupBox_10)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(-1, 4, -1, 4)
        self.labelSafe = QLabel(self.groupBox_10)
        self.labelSafe.setObjectName(u"labelSafe")
        self.labelSafe.setFont(font5)
        self.labelSafe.setInputMethodHints(Qt.ImhNone)
        self.labelSafe.setFrameShape(QFrame.NoFrame)
        self.labelSafe.setAlignment(Qt.AlignCenter)

        self.verticalLayout_16.addWidget(self.labelSafe)


        self.horizontalLayout.addWidget(self.groupBox_10)

        self.groupBoxSecurityScore = QGroupBox(self.frameSecurity)
        self.groupBoxSecurityScore.setObjectName(u"groupBoxSecurityScore")
        self.groupBoxSecurityScore.setGeometry(QRect(40, 90, 131, 41))
        self.groupBoxSecurityScore.setFont(font)
        self.groupBoxSecurityScore.setAlignment(Qt.AlignCenter)
        self.groupBoxSecurityScore.setFlat(False)
        self.verticalLayout_25 = QVBoxLayout(self.groupBoxSecurityScore)
        self.verticalLayout_25.setObjectName(u"verticalLayout_25")
        self.verticalLayout_25.setContentsMargins(-1, 4, -1, 4)
        self.labelSecurityScore = QLabel(self.groupBoxSecurityScore)
        self.labelSecurityScore.setObjectName(u"labelSecurityScore")
        self.labelSecurityScore.setFont(font5)
        self.labelSecurityScore.setInputMethodHints(Qt.ImhNone)
        self.labelSecurityScore.setFrameShape(QFrame.NoFrame)
        self.labelSecurityScore.setAlignment(Qt.AlignCenter)

        self.verticalLayout_25.addWidget(self.labelSecurityScore)


        self.horizontalLayout_7.addWidget(self.frameSecurity)

        self.stackedWidget.addWidget(self.widgetHealth)

        self.horizontalLayout_2.addWidget(self.stackedWidget)


        self.verticalLayout_2.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.buttonTabPasswords.setDefault(False)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBoxEntryTitle.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Password Manager", None))
        self.buttonTabPasswords.setText(QCoreApplication.translate("MainWindow", u"Passwords", None))
        self.buttonTabAddNew.setText(QCoreApplication.translate("MainWindow", u"Add New", None))
        self.buttonTabGenerate.setText(QCoreApplication.translate("MainWindow", u"Generate Password", None))
        self.buttonTabHealth.setText(QCoreApplication.translate("MainWindow", u"Password Health", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Password Manager", None))
        self.buttonLogOut.setText(QCoreApplication.translate("MainWindow", u"Log Out", None))
        self.editSearch.setText("")
        self.editSearch.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search Name", None))
        self.buttonDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.buttonCopyPassword.setText(QCoreApplication.translate("MainWindow", u"Copy Password", None))
        self.buttonEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.labelHeading_4.setText(QCoreApplication.translate("MainWindow", u"Passwords", None))
        self.labelHeading_5.setText(QCoreApplication.translate("MainWindow", u"Add a New Password", None))
        self.buttonAddPassword.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Title", None))
        self.comboBoxEntryTitle.setItemText(0, "")
        self.comboBoxEntryTitle.setItemText(1, QCoreApplication.translate("MainWindow", u"Alibaba", None))
        self.comboBoxEntryTitle.setItemText(2, QCoreApplication.translate("MainWindow", u"AliExpress", None))
        self.comboBoxEntryTitle.setItemText(3, QCoreApplication.translate("MainWindow", u"Amazon", None))
        self.comboBoxEntryTitle.setItemText(4, QCoreApplication.translate("MainWindow", u"Bing", None))
        self.comboBoxEntryTitle.setItemText(5, QCoreApplication.translate("MainWindow", u"Cash App", None))
        self.comboBoxEntryTitle.setItemText(6, QCoreApplication.translate("MainWindow", u"Discord", None))
        self.comboBoxEntryTitle.setItemText(7, QCoreApplication.translate("MainWindow", u"Ebay", None))
        self.comboBoxEntryTitle.setItemText(8, QCoreApplication.translate("MainWindow", u"Facebook", None))
        self.comboBoxEntryTitle.setItemText(9, QCoreApplication.translate("MainWindow", u"Flipkart", None))
        self.comboBoxEntryTitle.setItemText(10, QCoreApplication.translate("MainWindow", u"Foodpanda", None))
        self.comboBoxEntryTitle.setItemText(11, QCoreApplication.translate("MainWindow", u"Google", None))
        self.comboBoxEntryTitle.setItemText(12, QCoreApplication.translate("MainWindow", u"Instagram", None))
        self.comboBoxEntryTitle.setItemText(13, QCoreApplication.translate("MainWindow", u"Linkedin", None))
        self.comboBoxEntryTitle.setItemText(14, QCoreApplication.translate("MainWindow", u"McDonalds", None))
        self.comboBoxEntryTitle.setItemText(15, QCoreApplication.translate("MainWindow", u"Netflix", None))
        self.comboBoxEntryTitle.setItemText(16, QCoreApplication.translate("MainWindow", u"Reddit", None))
        self.comboBoxEntryTitle.setItemText(17, QCoreApplication.translate("MainWindow", u"Shopee", None))
        self.comboBoxEntryTitle.setItemText(18, QCoreApplication.translate("MainWindow", u"Snapchat", None))
        self.comboBoxEntryTitle.setItemText(19, QCoreApplication.translate("MainWindow", u"Spotify", None))
        self.comboBoxEntryTitle.setItemText(20, QCoreApplication.translate("MainWindow", u"Starbucks", None))
        self.comboBoxEntryTitle.setItemText(21, QCoreApplication.translate("MainWindow", u"Telegram", None))
        self.comboBoxEntryTitle.setItemText(22, QCoreApplication.translate("MainWindow", u"Tiktok", None))
        self.comboBoxEntryTitle.setItemText(23, QCoreApplication.translate("MainWindow", u"Twitch", None))
        self.comboBoxEntryTitle.setItemText(24, QCoreApplication.translate("MainWindow", u"Twitter", None))
        self.comboBoxEntryTitle.setItemText(25, QCoreApplication.translate("MainWindow", u"Uber", None))
        self.comboBoxEntryTitle.setItemText(26, QCoreApplication.translate("MainWindow", u"WeChat", None))
        self.comboBoxEntryTitle.setItemText(27, QCoreApplication.translate("MainWindow", u"WhatsApp", None))
        self.comboBoxEntryTitle.setItemText(28, QCoreApplication.translate("MainWindow", u"Wish", None))
        self.comboBoxEntryTitle.setItemText(29, QCoreApplication.translate("MainWindow", u"Wolt", None))
        self.comboBoxEntryTitle.setItemText(30, QCoreApplication.translate("MainWindow", u"Yahoo", None))
        self.comboBoxEntryTitle.setItemText(31, QCoreApplication.translate("MainWindow", u"Zoom", None))

        self.comboBoxEntryTitle.setCurrentText("")
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"URL", None))
        self.editEntryUrl.setText("")
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Username/Email", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Password", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Confirm password", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Password length", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Character types", None))
        self.checkBoxUpper.setText(QCoreApplication.translate("MainWindow", u"Uppercase (A-Z)", None))
        self.checkBoxLower.setText(QCoreApplication.translate("MainWindow", u"Lowercase (a-z)", None))
        self.checkBoxDigits.setText(QCoreApplication.translate("MainWindow", u"Digits (0-9)", None))
        self.checkBoxSymbols.setText(QCoreApplication.translate("MainWindow", u"Symbols (@%$!&?#)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Random password", None))
        self.labelGeneratedPwd.setText("")
        self.buttonRegenerate.setText(QCoreApplication.translate("MainWindow", u"Regenerate", None))
        self.buttonCopyRandomPassword.setText(QCoreApplication.translate("MainWindow", u"Copy Password", None))
        self.labelHeading_6.setText(QCoreApplication.translate("MainWindow", u"Generate a Random Password", None))
        self.labelHeading_7.setText(QCoreApplication.translate("MainWindow", u"Password Health", None))
        ___qtablewidgetitem = self.tableCompromised.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtablewidgetitem1 = self.tableCompromised.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Url", None));
        ___qtablewidgetitem2 = self.tableCompromised.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Password", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCompromised), QCoreApplication.translate("MainWindow", u"Compromised", None))
        ___qtablewidgetitem3 = self.tableReused.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtablewidgetitem4 = self.tableReused.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Url", None));
        ___qtablewidgetitem5 = self.tableReused.horizontalHeaderItem(2)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Password", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabReused), QCoreApplication.translate("MainWindow", u"Reused", None))
        ___qtablewidgetitem6 = self.tableWeak.horizontalHeaderItem(0)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtablewidgetitem7 = self.tableWeak.horizontalHeaderItem(1)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Url", None));
        ___qtablewidgetitem8 = self.tableWeak.horizontalHeaderItem(2)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Password", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWeak), QCoreApplication.translate("MainWindow", u"Weak", None))
        ___qtablewidgetitem9 = self.tableSafe.horizontalHeaderItem(0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtablewidgetitem10 = self.tableSafe.horizontalHeaderItem(1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"Url", None));
        ___qtablewidgetitem11 = self.tableSafe.horizontalHeaderItem(2)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"Password", None));
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSafe), QCoreApplication.translate("MainWindow", u"Safe", None))
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Total passwords", None))
        self.labelTotalPasswords.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"Compromised", None))
        self.labelCompromised.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("MainWindow", u"Reused", None))
        self.labelReused.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Weak", None))
        self.labelWeak.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Safe", None))
        self.labelSafe.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.groupBoxSecurityScore.setTitle(QCoreApplication.translate("MainWindow", u"Security Score", None))
        self.labelSecurityScore.setText(QCoreApplication.translate("MainWindow", u"0%", None))
    # retranslateUi

