# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSlider, QSpinBox, QStackedWidget,
    QTableWidget, QTableWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(660, 512)
        MainWindow.setAnimated(True)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"#buttonPasswords, #buttonAddNew, #buttonGenerate, #buttonSecurity {\n"
"	text-align: left;\n"
"	padding-left: 12px;\n"
"	padding-right: 12px;\n"
"}")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        font = QFont()
        font.setFamilies([u"Roboto"])
        self.frame.setFont(font)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frameSidebar = QFrame(self.frame)
        self.frameSidebar.setObjectName(u"frameSidebar")
        self.frameSidebar.setMinimumSize(QSize(160, 0))
        self.frameSidebar.setMaximumSize(QSize(160, 16777215))
        self.frameSidebar.setFont(font)
        self.frameSidebar.setFrameShape(QFrame.StyledPanel)
        self.frameSidebar.setFrameShadow(QFrame.Plain)
        self.frameSidebarButtons = QFrame(self.frameSidebar)
        self.frameSidebarButtons.setObjectName(u"frameSidebarButtons")
        self.frameSidebarButtons.setGeometry(QRect(0, 180, 160, 160))
        self.frameSidebarButtons.setMinimumSize(QSize(160, 160))
        self.frameSidebarButtons.setMaximumSize(QSize(160, 160))
        self.frameSidebarButtons.setFont(font)
        self.frameSidebarButtons.setFrameShape(QFrame.NoFrame)
        self.verticalLayout = QVBoxLayout(self.frameSidebarButtons)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonTabPasswords = QPushButton(self.frameSidebarButtons)
        self.buttonTabPasswords.setObjectName(u"buttonTabPasswords")
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonTabPasswords.sizePolicy().hasHeightForWidth())
        self.buttonTabPasswords.setSizePolicy(sizePolicy)
        self.buttonTabPasswords.setMinimumSize(QSize(0, 30))
        self.buttonTabPasswords.setFont(font)
        self.buttonTabPasswords.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabPasswords.setLayoutDirection(Qt.LeftToRight)
        self.buttonTabPasswords.setAutoFillBackground(False)
        self.buttonTabPasswords.setStyleSheet(u"")
        icon = QIcon()
        icon.addFile(u"icons/lock.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabPasswords.setIcon(icon)
        self.buttonTabPasswords.setIconSize(QSize(14, 14))
        self.buttonTabPasswords.setCheckable(False)
        self.buttonTabPasswords.setChecked(False)
        self.buttonTabPasswords.setAutoRepeat(False)
        self.buttonTabPasswords.setAutoExclusive(False)
        self.buttonTabPasswords.setFlat(False)

        self.verticalLayout.addWidget(self.buttonTabPasswords)

        self.buttonTabAddNew = QPushButton(self.frameSidebarButtons)
        self.buttonTabAddNew.setObjectName(u"buttonTabAddNew")
        sizePolicy.setHeightForWidth(self.buttonTabAddNew.sizePolicy().hasHeightForWidth())
        self.buttonTabAddNew.setSizePolicy(sizePolicy)
        self.buttonTabAddNew.setMinimumSize(QSize(0, 30))
        self.buttonTabAddNew.setFont(font)
        self.buttonTabAddNew.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabAddNew.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u"icons/add.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabAddNew.setIcon(icon1)
        self.buttonTabAddNew.setIconSize(QSize(14, 14))

        self.verticalLayout.addWidget(self.buttonTabAddNew)

        self.buttonTabGenerate = QPushButton(self.frameSidebarButtons)
        self.buttonTabGenerate.setObjectName(u"buttonTabGenerate")
        sizePolicy.setHeightForWidth(self.buttonTabGenerate.sizePolicy().hasHeightForWidth())
        self.buttonTabGenerate.setSizePolicy(sizePolicy)
        self.buttonTabGenerate.setMinimumSize(QSize(0, 30))
        self.buttonTabGenerate.setFont(font)
        self.buttonTabGenerate.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabGenerate.setStyleSheet(u"")
        icon2 = QIcon()
        icon2.addFile(u"icons/refresh.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabGenerate.setIcon(icon2)
        self.buttonTabGenerate.setIconSize(QSize(14, 14))

        self.verticalLayout.addWidget(self.buttonTabGenerate)

        self.buttonTabSecurity = QPushButton(self.frameSidebarButtons)
        self.buttonTabSecurity.setObjectName(u"buttonTabSecurity")
        sizePolicy.setHeightForWidth(self.buttonTabSecurity.sizePolicy().hasHeightForWidth())
        self.buttonTabSecurity.setSizePolicy(sizePolicy)
        self.buttonTabSecurity.setMinimumSize(QSize(0, 30))
        self.buttonTabSecurity.setFont(font)
        self.buttonTabSecurity.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonTabSecurity.setStyleSheet(u"")
        icon3 = QIcon()
        icon3.addFile(u"icons/security.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonTabSecurity.setIcon(icon3)
        self.buttonTabSecurity.setIconSize(QSize(14, 14))

        self.verticalLayout.addWidget(self.buttonTabSecurity)

        self.label = QLabel(self.frameSidebar)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 121, 61))
        font1 = QFont()
        font1.setFamilies([u"Roboto Medium"])
        font1.setPointSize(12)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        self.label.setFont(font1)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)

        self.horizontalLayout_2.addWidget(self.frameSidebar)

        self.stackedWidget = QStackedWidget(self.frame)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setFont(font)
        self.widgetPasswords = QWidget()
        self.widgetPasswords.setObjectName(u"widgetPasswords")
        self.verticalLayout_3 = QVBoxLayout(self.widgetPasswords)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.framePasswordDashboard = QFrame(self.widgetPasswords)
        self.framePasswordDashboard.setObjectName(u"framePasswordDashboard")
        self.framePasswordDashboard.setMinimumSize(QSize(0, 440))
        self.framePasswordDashboard.setMaximumSize(QSize(16777215, 440))
        self.framePasswordDashboard.setFrameShape(QFrame.NoFrame)
        self.framePasswordDashboard.setFrameShadow(QFrame.Raised)
        self.labelHeading_4 = QLabel(self.framePasswordDashboard)
        self.labelHeading_4.setObjectName(u"labelHeading_4")
        self.labelHeading_4.setGeometry(QRect(170, 5, 143, 16))
        font2 = QFont()
        font2.setFamilies([u"Roboto Medium"])
        font2.setPointSize(11)
        self.labelHeading_4.setFont(font2)
        self.labelHeading_4.setAlignment(Qt.AlignCenter)
        self.editSearch = QLineEdit(self.framePasswordDashboard)
        self.editSearch.setObjectName(u"editSearch")
        self.editSearch.setGeometry(QRect(40, 70, 401, 25))
        self.editSearch.setMinimumSize(QSize(0, 25))
        self.editSearch.setMaximumSize(QSize(16777215, 25))
        self.editSearch.setFont(font)
        self.editSearch.setFrame(True)
        self.editSearch.setClearButtonEnabled(True)
        self.frame_4 = QFrame(self.framePasswordDashboard)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(40, 400, 241, 31))
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.gridLayout = QGridLayout(self.frame_4)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonDelete = QPushButton(self.frame_4)
        self.buttonDelete.setObjectName(u"buttonDelete")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(25)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.buttonDelete.sizePolicy().hasHeightForWidth())
        self.buttonDelete.setSizePolicy(sizePolicy1)
        self.buttonDelete.setMinimumSize(QSize(0, 27))
        self.buttonDelete.setFont(font)
        self.buttonDelete.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u"icons/trash.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonDelete.setIcon(icon4)
        self.buttonDelete.setIconSize(QSize(13, 13))

        self.gridLayout.addWidget(self.buttonDelete, 0, 2, 1, 1)

        self.buttonCopy = QPushButton(self.frame_4)
        self.buttonCopy.setObjectName(u"buttonCopy")
        sizePolicy1.setHeightForWidth(self.buttonCopy.sizePolicy().hasHeightForWidth())
        self.buttonCopy.setSizePolicy(sizePolicy1)
        self.buttonCopy.setMinimumSize(QSize(0, 27))
        self.buttonCopy.setFont(font)
        self.buttonCopy.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u"icons/copy.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonCopy.setIcon(icon5)
        self.buttonCopy.setIconSize(QSize(13, 13))

        self.gridLayout.addWidget(self.buttonCopy, 0, 0, 1, 1)

        self.buttonEdit = QPushButton(self.frame_4)
        self.buttonEdit.setObjectName(u"buttonEdit")
        sizePolicy1.setHeightForWidth(self.buttonEdit.sizePolicy().hasHeightForWidth())
        self.buttonEdit.setSizePolicy(sizePolicy1)
        self.buttonEdit.setMinimumSize(QSize(0, 27))
        self.buttonEdit.setFont(font)
        self.buttonEdit.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u"icons/edit.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonEdit.setIcon(icon6)
        self.buttonEdit.setIconSize(QSize(13, 13))

        self.gridLayout.addWidget(self.buttonEdit, 0, 1, 1, 1)

        self.tablePasswords = QTableWidget(self.framePasswordDashboard)
        if (self.tablePasswords.columnCount() < 4):
            self.tablePasswords.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.tablePasswords.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tablePasswords.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tablePasswords.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tablePasswords.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tablePasswords.setObjectName(u"tablePasswords")
        self.tablePasswords.setGeometry(QRect(40, 110, 401, 271))
        font3 = QFont()
        font3.setPointSize(9)
        self.tablePasswords.setFont(font3)
        self.tablePasswords.setAutoScroll(False)
        self.tablePasswords.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tablePasswords.setTabKeyNavigation(True)
        self.tablePasswords.setProperty("showDropIndicator", True)
        self.tablePasswords.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tablePasswords.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablePasswords.verticalHeader().setVisible(False)

        self.verticalLayout_3.addWidget(self.framePasswordDashboard)

        self.stackedWidget.addWidget(self.widgetPasswords)
        self.widgetAdd = QWidget()
        self.widgetAdd.setObjectName(u"widgetAdd")
        self.verticalLayout_4 = QVBoxLayout(self.widgetAdd)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.frameAddPassword = QFrame(self.widgetAdd)
        self.frameAddPassword.setObjectName(u"frameAddPassword")
        self.frameAddPassword.setFont(font)
        self.frameAddPassword.setFrameShape(QFrame.NoFrame)
        self.frameAddPassword.setFrameShadow(QFrame.Raised)
        self.labelTitle = QLabel(self.frameAddPassword)
        self.labelTitle.setObjectName(u"labelTitle")
        self.labelTitle.setGeometry(QRect(40, 80, 33, 21))
        font4 = QFont()
        font4.setFamilies([u"Roboto"])
        font4.setPointSize(8)
        self.labelTitle.setFont(font4)
        self.labelTitle.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.labelUsername = QLabel(self.frameAddPassword)
        self.labelUsername.setObjectName(u"labelUsername")
        self.labelUsername.setGeometry(QRect(40, 200, 55, 20))
        self.labelUsername.setFont(font4)
        self.labelUsername.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.labelPassword = QLabel(self.frameAddPassword)
        self.labelPassword.setObjectName(u"labelPassword")
        self.labelPassword.setGeometry(QRect(40, 260, 54, 21))
        self.labelPassword.setFont(font4)
        self.labelPassword.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.labelHeading = QLabel(self.frameAddPassword)
        self.labelHeading.setObjectName(u"labelHeading")
        self.labelHeading.setGeometry(QRect(170, 30, 143, 18))
        self.labelHeading.setFont(font2)
        self.labelHeading.setAlignment(Qt.AlignCenter)
        self.editTitle = QLineEdit(self.frameAddPassword)
        self.editTitle.setObjectName(u"editTitle")
        self.editTitle.setGeometry(QRect(40, 100, 400, 25))
        self.editTitle.setFont(font4)
        self.editUsername = QLineEdit(self.frameAddPassword)
        self.editUsername.setObjectName(u"editUsername")
        self.editUsername.setGeometry(QRect(40, 220, 400, 25))
        self.editUsername.setFont(font4)
        self.editUrl = QLineEdit(self.frameAddPassword)
        self.editUrl.setObjectName(u"editUrl")
        self.editUrl.setGeometry(QRect(40, 160, 400, 25))
        self.editUrl.setFont(font4)
        self.labelUrl = QLabel(self.frameAddPassword)
        self.labelUrl.setObjectName(u"labelUrl")
        self.labelUrl.setGeometry(QRect(40, 140, 33, 21))
        self.labelUrl.setFont(font4)
        self.labelUrl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.frameButtons = QFrame(self.frameAddPassword)
        self.frameButtons.setObjectName(u"frameButtons")
        self.frameButtons.setGeometry(QRect(40, 330, 231, 41))
        self.frameButtons.setFont(font)
        self.frameButtons.setFrameShape(QFrame.NoFrame)
        self.frameButtons.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.frameButtons)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonAddPassword = QPushButton(self.frameButtons)
        self.buttonAddPassword.setObjectName(u"buttonAddPassword")
        self.buttonAddPassword.setMinimumSize(QSize(0, 27))
        self.buttonAddPassword.setCursor(QCursor(Qt.PointingHandCursor))

        self.horizontalLayout.addWidget(self.buttonAddPassword)

        self.buttonClear = QPushButton(self.frameButtons)
        self.buttonClear.setObjectName(u"buttonClear")
        self.buttonClear.setMinimumSize(QSize(0, 27))
        self.buttonClear.setCursor(QCursor(Qt.PointingHandCursor))

        self.horizontalLayout.addWidget(self.buttonClear)

        self.editPassword = QLineEdit(self.frameAddPassword)
        self.editPassword.setObjectName(u"editPassword")
        self.editPassword.setGeometry(QRect(41, 282, 400, 25))
        self.editPassword.setMinimumSize(QSize(0, 25))
        self.editPassword.setFont(font4)
        self.editPassword.setEchoMode(QLineEdit.Password)

        self.verticalLayout_4.addWidget(self.frameAddPassword)

        self.stackedWidget.addWidget(self.widgetAdd)
        self.widgetGenerate = QWidget()
        self.widgetGenerate.setObjectName(u"widgetGenerate")
        self.horizontalLayout_6 = QHBoxLayout(self.widgetGenerate)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.frameGenerate = QFrame(self.widgetGenerate)
        self.frameGenerate.setObjectName(u"frameGenerate")
        font5 = QFont()
        font5.setPointSize(10)
        self.frameGenerate.setFont(font5)
        self.frameGenerate.setFrameShape(QFrame.NoFrame)
        self.frameGenerate.setFrameShadow(QFrame.Raised)
        self.labelHeading_2 = QLabel(self.frameGenerate)
        self.labelHeading_2.setObjectName(u"labelHeading_2")
        self.labelHeading_2.setGeometry(QRect(140, 30, 202, 18))
        self.labelHeading_2.setFont(font2)
        self.labelHeading_2.setAlignment(Qt.AlignCenter)
        self.groupBox_2 = QGroupBox(self.frameGenerate)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(40, 80, 400, 71))
        self.groupBox_2.setFont(font)
        self.horizontalLayout_4 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.spinBox = QSpinBox(self.groupBox_2)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setMinimumSize(QSize(0, 25))
        self.spinBox.setFont(font)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(True)
        self.spinBox.setAccelerated(False)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMinimum(8)
        self.spinBox.setMaximum(50)
        self.spinBox.setValue(15)

        self.horizontalLayout_4.addWidget(self.spinBox)

        self.horizontalSlider = QSlider(self.groupBox_2)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setMinimumSize(QSize(0, 20))
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setCursor(QCursor(Qt.PointingHandCursor))
        self.horizontalSlider.setMinimum(8)
        self.horizontalSlider.setMaximum(50)
        self.horizontalSlider.setValue(15)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)

        self.horizontalLayout_4.addWidget(self.horizontalSlider)

        self.groupBox = QGroupBox(self.frameGenerate)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(40, 170, 400, 142))
        self.groupBox.setFont(font)
        self.verticalLayout_5 = QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.checkBoxUpper = QCheckBox(self.groupBox)
        self.checkBoxUpper.setObjectName(u"checkBoxUpper")
        self.checkBoxUpper.setFont(font4)
        self.checkBoxUpper.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxUpper)

        self.checkBoxLower = QCheckBox(self.groupBox)
        self.checkBoxLower.setObjectName(u"checkBoxLower")
        self.checkBoxLower.setFont(font4)
        self.checkBoxLower.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxLower)

        self.checkBoxDigits = QCheckBox(self.groupBox)
        self.checkBoxDigits.setObjectName(u"checkBoxDigits")
        self.checkBoxDigits.setFont(font4)
        self.checkBoxDigits.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxDigits)

        self.checkBoxSymbols = QCheckBox(self.groupBox)
        self.checkBoxSymbols.setObjectName(u"checkBoxSymbols")
        self.checkBoxSymbols.setFont(font4)
        self.checkBoxSymbols.setChecked(True)

        self.verticalLayout_5.addWidget(self.checkBoxSymbols)

        self.groupBox_3 = QGroupBox(self.frameGenerate)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(40, 370, 400, 71))
        self.groupBox_3.setFont(font)
        self.horizontalLayout_5 = QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.labelGeneratedPwd = QLabel(self.groupBox_3)
        self.labelGeneratedPwd.setObjectName(u"labelGeneratedPwd")
        self.labelGeneratedPwd.setFont(font4)
        self.labelGeneratedPwd.setCursor(QCursor(Qt.IBeamCursor))
        self.labelGeneratedPwd.setFrameShape(QFrame.StyledPanel)
        self.labelGeneratedPwd.setFrameShadow(QFrame.Plain)
        self.labelGeneratedPwd.setWordWrap(False)
        self.labelGeneratedPwd.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextSelectableByMouse)

        self.horizontalLayout_5.addWidget(self.labelGeneratedPwd)

        self.buttonCopyPwd = QPushButton(self.groupBox_3)
        self.buttonCopyPwd.setObjectName(u"buttonCopyPwd")
        self.buttonCopyPwd.setMinimumSize(QSize(30, 0))
        self.buttonCopyPwd.setMaximumSize(QSize(30, 30))
        self.buttonCopyPwd.setFont(font)
        self.buttonCopyPwd.setCursor(QCursor(Qt.PointingHandCursor))
        self.buttonCopyPwd.setIcon(icon5)
        self.buttonCopyPwd.setIconSize(QSize(10, 10))

        self.horizontalLayout_5.addWidget(self.buttonCopyPwd)

        self.buttonGeneratePwd = QPushButton(self.frameGenerate)
        self.buttonGeneratePwd.setObjectName(u"buttonGeneratePwd")
        self.buttonGeneratePwd.setGeometry(QRect(40, 330, 400, 27))
        self.buttonGeneratePwd.setFont(font)
        self.buttonGeneratePwd.setCursor(QCursor(Qt.PointingHandCursor))
        self.labelCopiedToClip = QLabel(self.frameGenerate)
        self.labelCopiedToClip.setObjectName(u"labelCopiedToClip")
        self.labelCopiedToClip.setGeometry(QRect(40, 440, 116, 31))
        font6 = QFont()
        font6.setFamilies([u"Roboto"])
        font6.setPointSize(8)
        font6.setItalic(False)
        self.labelCopiedToClip.setFont(font6)

        self.horizontalLayout_6.addWidget(self.frameGenerate)

        self.stackedWidget.addWidget(self.widgetGenerate)
        self.widgetSecurity = QWidget()
        self.widgetSecurity.setObjectName(u"widgetSecurity")
        self.horizontalLayout_7 = QHBoxLayout(self.widgetSecurity)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.frameSecurity = QFrame(self.widgetSecurity)
        self.frameSecurity.setObjectName(u"frameSecurity")
        self.frameSecurity.setFrameShape(QFrame.NoFrame)
        self.frameSecurity.setFrameShadow(QFrame.Raised)
        self.labelHeading_3 = QLabel(self.frameSecurity)
        self.labelHeading_3.setObjectName(u"labelHeading_3")
        self.labelHeading_3.setGeometry(QRect(190, 30, 100, 18))
        self.labelHeading_3.setFont(font2)
        self.labelHeading_3.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_7.addWidget(self.frameSecurity)

        self.stackedWidget.addWidget(self.widgetSecurity)

        self.horizontalLayout_2.addWidget(self.stackedWidget)


        self.verticalLayout_2.addWidget(self.frame)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.buttonTabPasswords.setDefault(False)
        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Password Manager", None))
        self.buttonTabPasswords.setText(QCoreApplication.translate("MainWindow", u"Passwords", None))
        self.buttonTabAddNew.setText(QCoreApplication.translate("MainWindow", u"Add New", None))
        self.buttonTabGenerate.setText(QCoreApplication.translate("MainWindow", u"Generate Password", None))
        self.buttonTabSecurity.setText(QCoreApplication.translate("MainWindow", u"Security Check", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Password Manager", None))
        self.labelHeading_4.setText(QCoreApplication.translate("MainWindow", u"Password Dashboard", None))
        self.editSearch.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.buttonDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.buttonCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.buttonEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        ___qtablewidgetitem = self.tablePasswords.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Title", None));
        ___qtablewidgetitem1 = self.tablePasswords.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Url", None));
        ___qtablewidgetitem2 = self.tablePasswords.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Username", None));
        ___qtablewidgetitem3 = self.tablePasswords.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Password", None));
        self.labelTitle.setText(QCoreApplication.translate("MainWindow", u"Title:", None))
        self.labelUsername.setText(QCoreApplication.translate("MainWindow", u"Username:", None))
        self.labelPassword.setText(QCoreApplication.translate("MainWindow", u"Password:", None))
        self.labelHeading.setText(QCoreApplication.translate("MainWindow", u"Add a New Password", None))
        self.labelUrl.setText(QCoreApplication.translate("MainWindow", u"URL:", None))
        self.buttonAddPassword.setText(QCoreApplication.translate("MainWindow", u"Add", None))
        self.buttonClear.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.labelHeading_2.setText(QCoreApplication.translate("MainWindow", u"Generate a Random Password", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Password Length:", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Character Types:", None))
        self.checkBoxUpper.setText(QCoreApplication.translate("MainWindow", u"Uppercase (A-Z)", None))
        self.checkBoxLower.setText(QCoreApplication.translate("MainWindow", u"Lowercase (a-z)", None))
        self.checkBoxDigits.setText(QCoreApplication.translate("MainWindow", u"Digits (0-9)", None))
        self.checkBoxSymbols.setText(QCoreApplication.translate("MainWindow", u"Symbols (!$%@#)", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Random Password:", None))
        self.labelGeneratedPwd.setText("")
        self.buttonCopyPwd.setText("")
        self.buttonGeneratePwd.setText(QCoreApplication.translate("MainWindow", u"Generate Password", None))
        self.labelCopiedToClip.setText("")
        self.labelHeading_3.setText(QCoreApplication.translate("MainWindow", u"Security Check", None))
    # retranslateUi

